######################################################################
# Automatically generated by qmake (3.0) Sat May 10 09:50:18 2014
######################################################################


QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = Client
INCLUDEPATH += .

# Input
HEADERS += mailer.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
